# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DP19r2UxoaMaQieyjJZ9FMGYEYwb7hCh
"""

from fastapi import FastAPI
import pandas as pd
import re
import argparse
import uvicorn
from typing import List
from pydantic import BaseModel

app = FastAPI()

class Files(BaseModel):
    file1: str
    file2: str

@app.post('/get_topic')
async def get_topic(files: Files) -> List[str]:
    cat_file = pd.ExcelFile(files.file1)
    sheet_to_df_map = {}
    for sheet_name in cat_file.sheet_names:
        sheet_to_df_map[sheet_name] = cat_file.parse(sheet_name)

    my_series = pd.Series(sheet_to_df_map)

    cat_file = my_series[my_series.notna()].to_dict()
    text_file = pd.read_excel(files.file2)
    text_file = text_file['Ärende'].to_list()

    def get_dict_key(dictionary) -> list:
        return list(dictionary.keys())

    cat_list = get_dict_key(cat_file)

    index_counter = 0

    parser = argparse.ArgumentParser(description="Script")
    parser.add_argument("--text")
    args, leftovers = parser.parse_known_args()

    s_text = text_file

    word_counter = 0

    cat_result = []
    result_list = []
    for n_of_text in s_text:
        for t in cat_list:
            r = re.findall(r'|'.join(cat_file[t]), n_of_text, re.IGNORECASE)
            if(r):
                if(t in cat_result):
                    result_list[cat_result.index(t)] = result_list[cat_result.index(t)]+len(r)
                else:
                    cat_result.append(t)
                    result_list.append(len(r))
        word_counter += 1

    html_list = []
    loop_counter = 0
    total_value = sum(result_list)
    for cat in cat_result:
        dt = f"{cat_result[loop_counter]} {round((result_list[loop_counter]/total_value)*100, 2)}%"
        html_list.append(dt)
        loop_counter+=1
    return html_list

if __name__ == "__main__":
    uvicorn.run(app, host="localhost", port=8000)